
language: ruby

rvm:
  #- 1.8.7 # no, since it doesn't get fun(a, *b, c) or fun0\n.fun1
  - 2.3.1
  - 2.4.2
  - 2.5.1
  - 2.7.1
  #- jruby-9.1.13.0
  - jruby-9.2.5.0

#matrix:
#  include:
#    - rvm: jruby-9.1.13.0
#    #- env: JRUBY_OPTS="--profile.api"

#before_install: gem install bundler
script: bundle exec rspec

branches:
  only:
    - master
  #except:
  #  - master

cache: bundler

#env:
#  - XX=0

